CREATE DATABASE IF NOT EXISTS mail_system DEFAULT CHARACTER SET utf8mb4;
USE mail_system;

CREATE TABLE IF NOT EXISTS emails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE
);
